# Generated by Django 4.1.7 on 2023-05-03 07:56

from django.db import migrations, models
import django.utils.timezone
import krishna.models


class Migration(migrations.Migration):

    dependencies = [
        ('krishna', '0006_auto_20200808_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=krishna.models.room_image_upload_path),
            preserve_default=False,
        ),
    ]
